In [1]:
import pandas as pd
import csv

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', None)

In [2]:
# Especificar os tipos exatos das colunas
dtype_mapping = {
    'DATA YYYY-MM-DD': 'string',
    'HORA UTC': 'string',
    'PRECIPITACÃO TOTAL HORÁRIO MM': 'float32',
    'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO HORARIA MB': 'float32',
    'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. AUT MB': 'float32',
    'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. AUT MB': 'float32',
    'RADIACAO GLOBAL KJ/M²': 'float32',
    'TEMPERATURA DO AR - BULBO SECO HORARIA °C': 'float32',
    'TEMPERATURA DO PONTO DE ORVALHO °C': 'float32',
    'TEMPERATURA MÁXIMA NA HORA ANT. AUT °C': 'float32',
    'TEMPERATURA MÍNIMA NA HORA ANT. AUT °C': 'float32',
    'TEMPERATURA ORVALHO MAX. NA HORA ANT. AUT °C': 'float32',
    'TEMPERATURA ORVALHO MIN. NA HORA ANT. AUT °C': 'float32',
    'UMIDADE REL. MAX. NA HORA ANT. AUT %': 'float32',
    'UMIDADE REL. MIN. NA HORA ANT. AUT %': 'float32',
    'UMIDADE RELATIVA DO AR HORARIA %': 'float32',
    'VENTO DIRECÃO HORARIA GR ° GR': 'float32',
    'VENTO RAJADA MAXIMA M/S': 'float32',
    'VENTO VELOCIDADE HORARIA M/S': 'float32',
    'REGIAO': 'string',
    'UF': 'string',
    'ESTACAO': 'string',
    'CODIGO (WMO)': 'string',
    'LATITUDE': 'float32',
    'LONGITUDE': 'float32',
    'ALTITUDE': 'float32',
    'DATA DE FUNDACAO': 'string',  # Pode ser convertido para datetime depois
    'YEAR': 'Int32'
}

unp_df = pd.read_csv(
    "all_data/csvs_processed/INMET_CO_DF_A001_BRASILIA_01-01-2001_A_31-12-2001.CSV", 
    #sep = ";",
    encoding='utf-8' , 
    encoding_errors='ignore'  # Ignora caracteres inválidos
)

# Caminho para o arquivo tratado
#file_path = 'all_data/csvs_concatenated/test_models/testa_modelo.csv.gz'

file_path = 'all_data/csvs_concatenated/testa_modelo.csv.gz'

# Carregar com dtype especificado
df = pd.read_csv(file_path)#, dtype=dtype_mapping)

# Converter colunas de data (se necessário)
#df['DATA DE FUNDACAO'] = pd.to_datetime(df['DATA DE FUNDACAO'], errors='coerce', dayfirst=True)

#print(df.dtypes)

In [ ]:
df.isnull().sum()

In [ ]:
unp_df.isnull().sum()

In [4]:
df.dtypes

DATA YYYY-MM-DD                                        object
HORA UTC                                               object
PRECIPITACÃO TOTAL HORÁRIO MM                         float64
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO HORARIA MB    float64
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. AUT MB           float64
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. AUT MB          float64
RADIACAO GLOBAL KJ/M²                                 float64
TEMPERATURA DO AR - BULBO SECO HORARIA °C             float64
TEMPERATURA DO PONTO DE ORVALHO °C                    float64
TEMPERATURA MÁXIMA NA HORA ANT. AUT °C                float64
TEMPERATURA MÍNIMA NA HORA ANT. AUT °C                float64
TEMPERATURA ORVALHO MAX. NA HORA ANT. AUT °C          float64
TEMPERATURA ORVALHO MIN. NA HORA ANT. AUT °C          float64
UMIDADE REL. MAX. NA HORA ANT. AUT %                  float64
UMIDADE REL. MIN. NA HORA ANT. AUT %                  float64
UMIDADE RELATIVA DO AR HORARIA %                      float64
VENTO DIRECÃO HORARIA GR ° GR                         float64
VENTO RAJADA MAXIMA M/S                               float64
VENTO VELOCIDADE HORARIA M/S                          float64
REGIAO                                                 object
UF                                                     object
ESTACAO                                                object
CODIGO (WMO)                                           object
LATITUDE                                              float64
LONGITUDE                                             float64
ALTITUDE                                              float64
YEAR                                                  float64
dtype: object

In [ ]:
df.shape

In [3]:
df.head()

,DATA YYYY-MM-DD,HORA UTC,PRECIPITACÃO TOTAL HORÁRIO MM,PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO HORARIA MB,PRESSÃO ATMOSFERICA MAX.NA HORA ANT. AUT MB,PRESSÃO ATMOSFERICA MIN. NA HORA ANT. AUT MB,RADIACAO GLOBAL KJ/M²,TEMPERATURA DO AR - BULBO SECO HORARIA °C,TEMPERATURA DO PONTO DE ORVALHO °C,TEMPERATURA MÁXIMA NA HORA ANT. AUT °C,TEMPERATURA MÍNIMA NA HORA ANT. AUT °C,TEMPERATURA ORVALHO MAX. NA HORA ANT. AUT °C,TEMPERATURA ORVALHO MIN. NA HORA ANT. AUT °C,UMIDADE REL. MAX. NA HORA ANT. AUT %,UMIDADE REL. MIN. NA HORA ANT. AUT %,UMIDADE RELATIVA DO AR HORARIA %,VENTO DIRECÃO HORARIA GR ° GR,VENTO RAJADA MAXIMA M/S,VENTO VELOCIDADE HORARIA M/S,REGIAO,UF,ESTACAO,CODIGO (WMO),LATITUDE,LONGITUDE,ALTITUDE,YEAR
0,2001-09-10,08:00,0.0,886.6,886.6,886.3,-9999.0,19.2,7.6,19.7,18.4,8.5,7.4,51.0,46.0,47.0,300.0,1.8,0.0,CO,DF,BRASILIA,A001,-15.789444,-47.925835,1159.54,2001.0
1,2001-08-20,12:00,0.0,894.9,894.9,894.3,1572.0,18.1,10.1,18.1,16.8,10.7,10.1,66.0,60.0,60.0,87.0,10.1,5.9,CO,DF,BRASILIA,A001,-15.789444,-47.925835,1159.54,2001.0
2,2001-09-07,14:00,0.0,888.9,889.0,888.8,3111.0,25.4,8.0,25.6,23.8,8.3,7.2,36.0,32.0,33.0,70.0,7.6,4.3,CO,DF,BRASILIA,A001,-15.789444,-47.925835,1159.54,2001.0
3,2001-11-16,18:00,0.0,884.2,884.9,884.2,1683.0,27.4,16.3,28.0,26.7,16.6,14.6,53.0,46.0,51.0,213.0,3.4,1.2,CO,DF,BRASILIA,A001,-15.789444,-47.925835,1159.54,2001.0
4,2001-05-19,07:00,0.0,888.4,888.4,888.3,-9999.0,16.5,15.2,17.1,16.4,15.5,14.9,93.0,90.0,92.0,167.0,2.9,0.9,CO,DF,BRASILIA,A001,-15.789444,-47.925835,1159.54,2001.0

In [ ]:
df.isnull().sum()

In [ ]:
unp_df.head(2)

In [ ]:
df_proc.shape

In [ ]:
df.isnull().sum()

In [ ]:
df_proc.isnull().sum()

In [ ]:
df_proc.dtypes

In [ ]:
import pandas as pd
import numpy as np

# Criar um DataFrame de exemplo
df = pd.DataFrame({
    'float_col': [1.1, 2.2, 3.3],
    'int_col': [1, 2, 3]
})

# Converter explicitamente
df['float_col'] = df['float_col'].astype('float32')
df['int_col'] = df['int_col'].astype('int32')

print("Tipos originais:")
print(df.dtypes)

# Salvar CSV
df.to_csv('test.csv', index=False)

# Ler CSV de volta
df_read = pd.read_csv('test.csv')

print("\nTipos após ler o CSV:")
print(df_read.dtypes)

# Agora vamos tentar salvar especificando o formato dos números
df.to_csv('test.csv', index=False, float_format='%.2f')
df_read = pd.read_csv('test.csv', dtype={'float_col': 'float32', 'int_col': 'int32'})

print("\nTipos após ler o CSV com dtype especificado:")
print(df_read.dtypes)